export enum ResponseCode {

  DRAWING_RECEIVED,
  DRAWN,
  DRAWN_ERROR,
  PARTY_CREATED,
  PARTY_CONNECTED,
  PARTY_DISCONNECTED,
  PARTY_CLOSED,
  PARTY_LIST,
  PARTY_CONNECT_ERROR,
  PARTY_ALREADY_CONNECTED,
  PARTY_NOT_CONNECTED,
  PARTY_DISCONNECT_ERROR,
  PARTY_ERROR,
  PARTY_LIMIT,
  PARTY_CLIENT_JOINED,
  PARTY_CLIENT_LEFT,

}
